apiVersion: apps/v1
kind: Deployment
metadata:
  name: nix-it-lab-deployment
  namespace: default
  labels:
    app: nix-it-lab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nix-it-lab
  template:
    metadata:
      labels:
        app: nix-it-lab
    spec:
      containers:
        - name: nix-it-lab
          image: nitace/nix_it_lab:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
